name: uber_clone_core
description: "A core package project for Uber Clone, containing the business logic layer with service classes, repositories, and the data layer"
version: 0.0.1  
# homepage:
 
environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  geocoding:  ^3.0.0
  geolocator: ^12.0.0
  intl: ^0.20.2
  logger: ^2.4.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.3.2
  google_places:
    path: ../google_place/  
  flutter_polyline_points: ^2.1.0
  synchronized: ^3.2.0
  flutter_typeahead: ^5.2.0  
  google_maps_flutter: ^2.9.0
  flutter_dotenv: ^5.1.0
  flutter_getit: ^3.0.1
  validatorless: ^1.2.3
  mobx: ^2.4.0
  firebase_messaging: ^15.2.5
  decimal: ^3.2.1
  flutter_local_notifications: ^19.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1  
  build_runner: ^2.4.12  
  mocktail: ^1.0.4

  
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/fundo.png
    - assets/images/logo.png
    - assets/images/passageiro.png
    - assets/images/motorista.png
    - assets/images/user.png
    - assets/images/destino.png
    - assets/images/carro.png
    - assets/images/destino.png
    - assets/images/destination1.png
    - assets/images/destination2.png
    - assets/images/uber_car.jpg
    - assets/images/map_car.png
    - assets/images/uber_moto.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
